# =============================================================================
# TERRAFORM AWS EMAIL INFRASTRUCTURE - OUTPUTS
# =============================================================================

output "email_address" {
  description = "The full email address created (e.g., info@example.com)"
  value       = local.email_address
}

output "domain_name" {
  description = "The domain name"
  value       = var.domain_name
}

output "workmail_org_id" {
  description = "The WorkMail organization ID"
  value       = local.effective_org_id
}

output "workmail_alias" {
  description = "The WorkMail organization alias"
  value       = local.workmail_alias
}

output "workmail_user" {
  description = "The WorkMail username"
  value       = var.workmail_user
}

output "zone_id" {
  description = "The Route 53 hosted zone ID"
  value       = data.aws_route53_zone.this.zone_id
}

output "dns_records" {
  description = "DNS records created for WorkMail verification"
  value = {
    txt = {
      name  = data.external.workmail_domain.result.txt_name
      value = data.external.workmail_domain.result.txt_value
      type  = "TXT"
    }
    cname = {
      name  = data.external.workmail_domain.result.cname_name
      value = data.external.workmail_domain.result.cname_value
      type  = "CNAME"
    }
    mx = {
      name  = data.external.workmail_domain.result.mx_name
      value = data.external.workmail_domain.result.mx_value
      type  = "MX"
    }
  }
}

# Output for copy-paste into AFT account request
output "aft_account_request_snippet" {
  description = "Copy this snippet to your AFT account request main.tf"
  value       = <<-EOT
    # =============================================================================
    # AFT Account Request for ${var.domain_name}
    # =============================================================================
    # Generated by terraform-aws-email-infra module
    # Email: ${local.email_address}
    # WorkMail Org: ${local.effective_org_id}
    # =============================================================================
    
    module "${local.workmail_alias}" {
      source = "./modules/aft-account-request"
    
      control_tower_parameters = {
        AccountEmail              = "${local.email_address}"
        AccountName               = "${local.workmail_alias}"
        ManagedOrganizationalUnit = "REPLACE_WITH_OU_ID"  # e.g., "ou-xxxx-xxxxxxxx" or "Sandbox"
        SSOUserEmail              = "${local.email_address}"
        SSOUserFirstName          = "REPLACE_FIRST_NAME"
        SSOUserLastName           = "REPLACE_LAST_NAME"
      }
    
      account_tags = {
        "Opportunity" = "true"
        "Domain"      = "${var.domain_name}"
      }
    
      change_management_parameters = {
        change_requested_by = "Opportunity Portal"
        change_reason       = "Self-service account creation"
      }
    
      custom_fields = {
        group = "non-prod"
      }
    
      account_customizations_name = "sandbox"
    }
  EOT
}

# Machine-readable output for automation
output "aft_module_config" {
  description = "Machine-readable AFT module configuration for automation"
  value = {
    module_name = local.workmail_alias
    control_tower_parameters = {
      AccountEmail              = local.email_address
      AccountName               = local.workmail_alias
      ManagedOrganizationalUnit = null  # To be filled by caller
      SSOUserEmail              = local.email_address
      SSOUserFirstName          = null  # To be filled by caller
      SSOUserLastName           = null  # To be filled by caller
    }
    account_tags = {
      Opportunity = "true"
      Domain      = var.domain_name
    }
  }
}
